spring.profiles.active=prod

server.port=9483

# Hibernate Configuration
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Hibernate DDL Auto Configuration
spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB


#For local system
#school.img.local.path = C:\\Users\\sbhowmik\\Desktop\\images\\school_image\\
school.img.local.path = C:\\Users\\sbhowmik\\Desktop\\images\\school_image\\
student.img.local.path=C:\\Users\\sbhowmik\\Desktop\\images\\student_images\\
student.documents.local.path=C:\\Users\\sbhowmik\\Desktop\\images\\student_documents\\
staff.img.local.path=C:\\Users\\sbhowmik\\Desktop\\images\\staff_images\\
driver.img.local.path=C:\\Users\\sbhowmik\\Desktop\\images\\driver_images\\
parent.img.local.path=C:\\Users\\sbhowmik\\Desktop\\images\\parent_images\\
subject.syllabus.local.path=C:\\Users\\sbhowmik\\Desktop\\images\\subject_syllabus\\

#for pdf uploading
file.upload-dir=C:\\Users\\sbhowmik\\Desktop\\images\\homework\\
# Path for student_excel folder
student.excel.path=C:\\Users\\sbhowmik\\Desktop\\images\\student_excel\\

#paths for public and private key
private.key.path=C:\\Users\\sbhowmik\\SchoolMgmt\\eduGenius\\src\\main\\java\\com\\sms\\private_key.der
public.key.path=C:\\Users\\sbhowmik\\SchoolMgmt\\eduGenius\\src\\main\\java\\com\\sms\\public_key.der

#app.medhapro.com
# Paths for images
#school.img.local.path = /home/ubuntu/medhapro/images/school_logo/
#student.img.local.path = /home/ubuntu/medhapro/images/student/
#student.documents.local.path=/home/ubuntu/medhapro/images/student_documents/
#staff.img.local.path = /home/ubuntu/medhapro/images/staff/
#driver.img.local.path = /home/ubuntu/medhapro/images/drivers/
#parent.img.local.path=/home/ubuntu/medhapro/images/parent_images/

# Path for PDF uploading
#file.upload-dir = /home/ubuntu/medhapro/images/homework/
# Path for student_excel folder
#student.excel.path=/home/ubuntu/medhapro/student_excel/

#paths for public and private key
#private.key.path=/home/ubuntu/medhapro/java/keyFolder/private_key.der
#public.key.path=/home/ubuntu/medhapro/java/keyFolder/public_key.der

#erp.medhapro.com
#school.img.local.path = /home/ubuntu/medhapro_erp/images/school_logo/
#student.img.local.path = /home/ubuntu/medhapro_erp/images/student/
#student.documents.local.path=/home/ubuntu/medhapro_erp/images/student_documents/
#staff.img.local.path = /home/ubuntu/medhapro_erp/images/staff/
#driver.img.local.path = /home/ubuntu/medhapro_erp/images/drivers/
#parent.img.local.path=/home/ubuntu/medhapro_erp/images/parent_images/

# Path for PDF uploading
#file.upload-dir = /home/ubuntu/medhapro_erp/images/homework/
# Path for student_excel folder
#student.excel.path=/home/ubuntu/medhapro_erp/student_excel/

#private.key.path=/home/ubuntu/medhapro_erp/java/keyFolder/private_key.der
#public.key.path=/home/ubuntu/medhapro_erp/java/keyFolder/public_key.der



# Email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=medhapro360@gmail.com
spring.mail.password=oadf ovhj tqzd tibd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true