# DataSource Configuration server
#server.port=9483
#spring.datasource.url=jdbc:postgresql://10.0.142.233:5432/SchoolMgmt
#spring.datasource.username=postgres
#spring.datasource.password=@#$%CDdfscldmswrtfDDcf@#$oldfne
#spring.datasource.schema = medhapro
#spring.datasource.schema = demo

# DataSource Configuration server for erp.medhapro.com
#server.port=9483
#server.port=9486
#spring.datasource.url=jdbc:postgresql://10.0.142.233:5432/erp_schoolmgmt
#spring.datasource.username=erp_schoolmgmt
#spring.datasource.password=Cspl#123^
#spring.datasource.schema = medhapro

# DataSource Configuration server for demo.medhapro.com
#server.port=9486
server.port=9486
spring.datasource.url=jdbc:postgresql://10.0.136.112:5432/schoolmgmt
spring.datasource.username=schoolmgmt
spring.datasource.password=Cspl#123^
spring.datasource.schema = medhapro