package com.sms.appenum;

public enum Message {
    LOGIN_SUCCESS("Login successful"),
    LOGIN_FAILED("Invalid login details"),
    ADD_STUDENT_SUCCESS("Student details is added successfully"),
    ADD_STUDENT_FAILED("Student details is not added"),
    SEARCH_STUDENT_SUCCESS("Student details is fetched successfully"),
    SEARCH_STUDENT_FAILED("Student details not found"),
    ADD_ADMIN_SUCCESS("Admin details is added successfully"),
    ADD_ADMIN_FAILED("Admin details is not added"),
    ADD_ACCOUNTANT_SUCCESS("Accountant details is added successfully"),
    ADD_ACCOUNTANT_FAILED("Accountant details is not added"),
    ADD_TEACHER_SUCCESS("Teacher details is added successfully"),
    ADD_TEACHER_FAILED("Teacher details is not added"),
    ADD_IMAGE_SUCCESS("Image uploaded successfully"),
    ADD_IMAGE_FAILED("Image is not uploaded"),
    DELETE_STUDENT_SUCCESS("Student details is deleted successfully"),
    DELETE_STUDENT_FAILED("Student details is not deleted"),
    DELETE_TEACHER_SUCCESS("Teacher details is deleted successfully"),
    DELETE_TEACHER_FAILED("Teacher details is not deleted"),
    DELETE_CLASS_SUCCESS("Class is deleted successfully"),
    DELETE_CLASS_FAILED("Class is not deleted"),
    DELETE_SUBJECT_SUCCESS("Subject is deleted successfully"),
    DELETE_SUBJECT_FAILED("Subject is not deleted"),
    DELETE_SESSION_SUCCESS("Session is deleted successfully"),
    DELETE_SESSION_FAILED("Session is not deleted"),
    DELETE_SCHOOL_SUCCESS("School details is deleted successfully"),
    DELETE_SCHOOL_FAILED("School details is not deleted"),
    DELETE_SECTION_SUCCESS("Section is deleted successfully"),
    DELETE_SECTION_FAILED("Section is not deleted"),
    DELETE_BANKDETAILS_SUCCESS("Bank details is deleted successfully"),
    DELETE_STAFFDESIG_SUCCESS("Delete staff designation success"),
    DELETE_STAFFDESIG_FAILED("Staff designation is not deleted"),
    DELETE_STAFFDEPARTMENT_SUCCESS("Staff designation is deleted successfully"),
    DELETE_STAFFDEPARTMENT_FAILED("Staff designation is not deleted"),
    DELETE_HOLIDAY_DETAILS_SUCCESS("Holiday details is deleted"),
    DELETE_HOLIDAY_DETAILS_FAILED("Holiday details is not deleted"),
    DELETE_BANKDETAILS_FAILED("Bank details is not deleted"),
    DELETE_ALLOCATED_SUBJECT_SUCCESS("Allocated subject is deleted"),
    DELETE_ALLOCATED_SUBJECT_FAILED("Allocated subject is not deleted"),
    DELETE_STAFF_SUCCESS("Staff deletion successful"),
    DELETE_STAFF_FAILED ("Staff deletion failed"),
    DELETE_FREQUENCY_SUCCESS ("Frequency is deleted successfully"),
    DELETE_FREQUENCY_FAILED("Frequency is not deleted"),
    DELETE_FEE_SUCCESS("School fee is deleted successfully"),
    DELETE_FEE_FAILED("School fee is not deleted"),
    DELETE_DISCOUNT_SUCCESS("Discount code is deleted successfully"),
    DELETE_DISCOUNT_FAILED("Discount code is not deleted"),
    FEE_ASSIGNMENT_FAILED("Already assigned"),
    SESSION_ADDITION_FAILED("Already exists"),
    INTERNAL_SERVER_ERROR("Internal server error"),
    DELETE_CLASS_TEACHER_SUCCESS("Class teacher allocation deleted successfully"),
    DELETE_CLASS_TEACHER_FAILED("Class teacher allocation is not deleted"),
    DELETE_CLASS_SUBJECT_TEACHER_ALLOCATION_SUCCESS("Class SUBJECT teacher allocation deleted successfully"),
    DELETE_CLASS_SUBJECT_TEACHER_ALLOCATION_FAILED("Class SUBJECT teacher allocation is not deleted "),
    ADD_PDF_SUCCESS("Home work pdf added successfully"),
    ADD_PDF_FAILED("Home work pdf FAILED"),
    DELETE_HOMEWORK_SUCCESS("Home work deleted successfully"),
    DELETE_HOMEWORK_FAILED("Home work is not deleted"),
    DELETE_VEHICLE_SUCCESS("Vehicle is deleted successfully"),
    DELETE_VEHICLE_FAILED("Vehicle is not deleted"),
    DELETE_DRIVER_SUCCESS("Driver details is deleted successfully"),
    DELETE_DRIVER_FAILED("Driver details is not deleted"),
    DELETE_EXAM_MEETING_SUCCESS("exam meeting is deleted successfully"),
    DELETE_EXAM_MEETING_FAILED("exam meeting is NOT deleted"),
    DELETE_ROUTE_SUCCESS("Route is deleted successfully"),
    DELETE_ROUTE_FAILED("Route is not deleted"),
    DELETE_TRANSPORT_ALLOCATION_SUCCESS("Transport allocation is deleted successfully"),
    DELETE_TRANSPORT_ALLOCATION_FAILED("Transport allocation is not deleted"),
    DELETE_SCHEDULE_EXAM_SUCCESS("Schedule exam is deleted successfully"),
    DELETE_SCHEDULE_EXAM_FAILED("Schedule exam is not deleted"),
    DELETE_EXAM_MARKS_SUCCESS("Exam marks is deleted successfully"),
    DELETE_EXAM_MARKS_FAILED("Exam marks is not deleted"),
    DELETE_STAFF_SALARY_SUCCESS("Staff salary is deleted successfully"),
    DELETE_STAFF_SALARY_FAILED("Staff salary is not deleted"),
    DELETE_BOOK_CATEGORY_SUCCESS("Book category is deleted successfully"),
    DELETE_BOOK_CATEGORY_FAILED("Book category is not deleted "),
    DELETE_ADD_BOOK_SUCCESS("Book is deleted successfully"),
    DELETE_ADD_BOOK_FAILED("Book is not deleted"),
    DELETE_ISSUE_BOOK_SUCCESS("issue book is deleted successfully"),
    DELETE_ISSUE_BOOK_FAILED("issue book is not deleted"),
    DELETE_INVENTORY_CATEGORY_SUCCESS("Category is deleted successfully"),
    DELETE_INVENTORY_CATEGORY_FAIELD("Category is not deleted"),
    DELETE_BOOK_ITEMS_SUCCESS("Book items is deleted successfully"),
    DELETE_BOOK_ITEMS_FAILED("Book items is failed to delete"),
    DELETE_SUPPLIER_DETAILS_SUCCESS("Supplier is deleted successfully"),
    DELETE_SUPPLIER_DETAILS_FAIELD("Supplier is not deleted"),
    DELETE_FUEL_EXPENSE_SUCCESS("Fuel expense is deleted successfully"),
    DELETE_FUEL_EXPENSE_FAILED("Fuel expense is not deleted"),
    DELETE_EXPENSE_TYPE_SUCCESS("Expense type is deleted successfully"),
    DELETE_EXPENSE_TYPE_FAILED("Expense type is not deleted"),
    DELETE_ADD_EXPENSE_SUCCESS("Expense is deleted successfully"),
    DELETE_ADD_EXPENSE_FAILED("Expense is not deleted"),
    DELETE_USER_SUCCESS("User is deleted successfully"),
    DELETE_USER_FAILED("User is not deleted"),
    DELETE_PARENT_DETAILS_SUCCESS("Parent details is deleted successfully"),
    DELETE_PARENT_DETAILS_FAILED("Parent details is not deleted");

    private final String value;
    public String val(){return value;}

    Message(String value) {
        this.value = value;
    }
}
